### ISSUE TITLE
Create a delta modifier for bodies

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/Jump#13]
Not sure if we want this, but it could be a cool feature to add:

Basically just add a property that multiplies the delta for a given body. An example of this would be a slow-mo effect for an enemy if you hit them with an ice attack. You set their delta mod to .5 and they move at half speed now until the slow wears off.

An opposing example would be a 'focus' ability that the main player gets. When he uses it, the world slows down and he still moves the same speed (think matrix Neo battles). This could be achieved by setting the delta mod on all other bodies in the world OR by dropping the delta sent to world.step() and giving the player a delta mod to cancel out the world slowing down.

Could open for some interesting gameplay mechanics if we do it.

**Comment by Kenoshen** [comment]
This sounds like an awesome idea. But I have no idea how practical it would be to implement. Sounds hard >.<

**Comment by MondayHopscotch** [comment]
The more I think of this -- I think this should be handle-able by the game, and not the engine. Pretty one-off idea for the engine to have in it. Recreate an issue if we find a real need for this.
