### ISSUE TITLE
Background layer crash

### ISSUE THREAD

**Issue by nandemoguy** [bitDecayGames/Jump#211]
Trying to draw in the background layer crashes hard. 

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.OutOfMemoryError: Java heap space
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by nandemoguy** [comment]
Starting editor, create dirt 
Switch to layers
Select background
Select Create
Draw Dirt
Crash

**Comment by nandemoguy** [comment]
Starting editor, create dirt 
Switch to layers
Select background
Select Create
Draw Dirt
Crash

**Comment by Kenoshen** [comment]
Probably creating a BitmapFont somewhere in your update. 😜

**Comment by MondayHopscotch** [comment]
Well.... there is a memory leak of some sort in there. Will compare to older versions to see what is causing that.

I can't get it to crash, however. @nandemoguy, did you see this problem immediately after opening it? Or had it been sitting open for a while, by chance?

**Comment by nandemoguy** [comment]
If I do those exact steps it crashes every tjme

**Comment by MondayHopscotch** [comment]
This is the same computer you brought to work on Sporg's, yeah?

Looks like old versions had the same memory leak problem I'm seeing now - so I'm not going to worry about it for now. Still looking into why drawing  background tiles is blowing up on you.

**Comment by nandemoguy** [comment]
Yeah same comp. Maybe in a while we can screenshare

**Comment by MondayHopscotch** [comment]
I'll be on all day, so if you find some free time, just lemme know.
