### ISSUE TITLE
Allow editor to be run at different resolutions

### ISSUE THREAD

**Issue by Kenoshen** [bitDecayGames/Jump#224]
Currently the editor is kinda hardcoded to a 1600:900 resolution.  The problem is that on my computer that equates to a full screen.  I'd like to be able to run the editor at a smaller resolution without losing buttons from the shrunk window.  Even if it meant that the buttons and text were smaller, I'd be ok with that.

**Comment by MondayHopscotch** [comment]
I tried to make the ui dynamic when I first built it, but failed. I can
revisit and see if I can make it work again.
