### ISSUE TITLE
Allow game to provide objects to the editor

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/Jump#25]
~~A level editor isn't going to do us too much good if we have to manually strap all the graphics onto objects by modifying the json files. So we need some way to import images so the editor can save what graphic is to be used for a given body.~~

~~At a bare minimum we will need a way to attach level assets (ground tile sets) to the level objects in the editor. Any additional assets will be addressed as needed in future issues.~~

The needs of this have changed. Since now we will be having a game create a level editor inside of it, all we need is a way for outside code to give us a list of objects that we want to be able to use in the editor.

This list can include very basic data such as a fixed size (if there is one), an ID so the editor can attach it to the level object so the game can parse it out into the world, and a textureRegion/name so the editor can display it in the UI easily.

**Comment by MondayHopscotch** [comment]
In thinking on this, is there a reason we can't just use the same atlas as we plan on using in the game? At least for the ground tiles? As long as we define a specific format for the pieces, it should work out just fine.

**Comment by MondayHopscotch** [comment]
Been thinking on this even more.

I think the easiest thing we can do is to just let the editor be launched from inside our game. We can have a simple object pattern so we can just register any objects we want to use in the editor from our game's code.

This would let us have access to the texture regions without any extra special code, and it would also let us define the actual level object we want to be present in our game.

So new acceptance criteria:
* Have hook to register custom objects with the editor
* Have (for now) a super crude display to show registered objects from within the editor

**Comment by Kenoshen** [comment]
Maybe you could do something like package the level files with the art assets in a byte file. Just come up with a simple protocol (like, 4 bytes for size of the thing, 1 byte for the type of thing, then the array of bytes for what ever thing) so when you parse it all you'd have a level(s) and images with names that the levels reference. So in your game you just pull in the level parsing module and the physics stuff, you wouldn't have to rely on the level editor module. But this might be a YAGNI moment. Maybe more of a nice to have.

**Comment by MondayHopscotch** [comment]
Yeah, it's going to be weird to solve it and keep things decoupled.  I had another issue (issue #36) to just write down another idea I had about how to accomplish this. I think for now I'm just going to let it soak and see what my brain comes up with for it on the back burner.

To keep a good separation, some sort of protocol like you mentioned would be a good route to explore. I'd be curious to see how we tackle the translation layer (or level parsing module).

This also might also be a good time to expand the libgdx module, potentially -- or to build some basic level parsing pieces into it if we go the byte markers route. Have some more-specific LevelObjects that have TextureRegion's associated with them and such.

**Comment by MondayHopscotch** [comment]
Over the weekend, I came up with a pattern that I think will work quite well for this. With the changes made in #36, rendering responsibilities are now pushed onto the game instead of the editor code.

With my changes in #44 the editor will now only be responsible for rendering the debug data. This means that the editor doesn't need knowledge of any art assets -- Just the object data needed for the physics world.

There will be a few cases where the editor will need some extra metadata hints, those are namely:

* What tileset level tiles are using (only needs an ID, the actual job of turning this into a texture region is left up to the game to do)
* Some sort of Tileset notion for moving platforms
* An identifier for any misc level objects so that the game knows what they are once it parses the level

Outside of just strapping these "ID's" to the level objects, the editor doesn't need to know anything about them -- just where to place them in the world.

I think we are very close to having the ability to actually use this inside of a game.
