### ISSUE TITLE
Bring back BitBodyProps (or something similar)

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/Jump#45]
Since the editor is no longer dealing with BitBody's directly, the BitBodyProps gives us a really nice avenue for handling properties that can apply to a given BitBody.

The use-case I have right now is the player spawn can have the specs of how the player should be created in the level. So the spawn point acts as a location and specs for a player to be created. This allows us to stay entirely disconnected from the BitBody and the likes. It also gives us a really nice object to persist because it has no state -- just data.

**Comment by MondayHopscotch** [comment]
@Kenoshen I wanted to chat with you about this one to see if this is something you agree with or not.

Introducing the BitBodyProps class obviously makes a lot of calls to body.properties.<blah> instead of just calling something on the body -- but it does give us a really nice separation of state vs data. (Data being stats in this case; jump strength, max speed, etc).

I think it will allow for a nice way to separate things for the editor to be handling.

Thoughts?

**Comment by Kenoshen** [comment]
I agree that it is annoying when you always have to do the whole body.properties. However, the body of a player will most likely be wrapped in a MyAwesomeJavaGamePlayer.java class anyways. So you will probably only need to interface directly with the body and its properties in a small number of places. If adding the body props back in makes more sense than leaving it out then go for it. 

Ps. You are kicking ass on this project! I wish I was more help but dude you are knocking this one out of the park all on your own. I know how tough it can be to stay motivated for so long on something like this. Great work!

**Comment by MondayHopscotch** [comment]
Yeah, i feel that the game (whatever it may be) won't really need to pay *much* attention to the properties object.

But by introducing it back into it, the editor now has a nice data object to modify. Since the editor now no longer has any BitBody knowledge whatsoever (the editor just places LevelObejct's into a Level, and the game is now what is building the actual BitBody objects), it just seems like they have a place now again.

I'll play with introducing them again and see if it feels right.

And thanks, man! I got over a few humps that were previously keeping me from staying motivated no this thing -- and having the GitHub issues page has really helped to make sure I'm staying focused and doing things in digestible chunks. But honestly, just knowing that emails are going out when I tag you in things is plenty helpful enough to know that there is at least still some visibility into the motion of this project.

**Comment by MondayHopscotch** [comment]
I've been thinking on this even more -- and I think I'm leaning towards putting a set of properties on the spawn point of the level. Not sure if this makes sense, but it does seem to keep the data where it belongs since the editor only knows about the spawn point.

But if we have a properties object, then a given game can have tuned 'player property' files that they can load and stick onto spawn points as an easy way to use the editor.

**Comment by MondayHopscotch** [comment]
Currently experimenting with this in a local branch. Might also introduce changing how spawn points work along with a few other minor things.
