### ISSUE TITLE
Add tile transition data

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/Jump#55]
Not sure if this should be something the engine/editor can set for us, such as diagonal neighbor values (nValue on TileObjects), or if we should leave this up to the game to do -- but I'm leaning toward just handling it in the Jump code.

The first passthrough, we just need a way to do transition tiles so that when we change tilesets we don't just have hard lines along tile boundaries.

**Comment by Kenoshen** [comment]
'Could' use a shader for this. Maybe to start out just do a straight blend on the tiles like:

AA, AA, Aa, ab, bB, BB BB

Or even:

AA, AB, BB

But... Shaders can suck balls to make, so you might be better off just including transition tiles as part of a given tile set. I'm not sure which would really be a better use of time.

**Comment by MondayHopscotch** [comment]
I hadn't even thought of doing a shader for it. Could be interesting if we find the time.

**Comment by MondayHopscotch** [comment]
Neighbor data is already discoverable from what we save into a given level. I'm in the mindset that this should be the responsibility of the game to handle knowing when to render transition tiles, so I'm going to nix this from this project.
