### ISSUE TITLE
Add some sort of save dialog if user exits with unsaved changes

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/Jump#85]
Pretty straight-forward user expectation. Don't let them exit without offering to save the level.

If we want to go super cheap with this story -- we can just make it save a file "level<timestamp>" when the editor closes. I just want to make sure we aren't going to accidentally lose data if a user accidentally clicks 'exit' or closes the app unintentionally.

**Comment by Kenoshen** [comment]
Auto save is probably one of my favorite features in a text editor. It would be great to just save a level if the app shuts down in any way. And if they haven't saved the level already then save it with a temp.level name or something. That would be a great feature.

**Comment by MondayHopscotch** [comment]
Agreed. I'll take care of this tonight. Should be super quick.
