### ISSUE TITLE
Moving platforms should be able to launch player up

### ISSUE THREAD

**Issue by DynamicTim** [bitDecayGames/Jump#97]
Currently if a player is standing on a moving platform that is supposed to act like a launcher to shoot them up, they are just glued to it and it feels a little weird compared to the rest of the physics in the game.

We should be able to shoot the player into the sky.

**Comment by MondayHopscotch** [comment]
One thing we need to make a decision on is how to handle when a moving platform is going down. Should players be glued to it then? 

If not, there are some physics bugs we will need to work out.
